/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sudoku;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jTextField12 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setBackground(new java.awt.Color(186, 186, 186));
        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 59, 39));

        jTextField2.setBackground(new java.awt.Color(186, 186, 186));
        jTextField2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 59, 39));

        jTextField3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField3.setText("4");
        jTextField3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, 59, 39));

        jTextField4.setBackground(new java.awt.Color(186, 186, 186));
        jTextField4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 59, 39));

        jTextField5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jTextField5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField5.setText("1");
        jTextField5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 272, 59, 39));

        jTextField6.setBackground(new java.awt.Color(186, 186, 186));
        jTextField6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jTextField6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 272, 59, 39));

        jTextField7.setBackground(new java.awt.Color(186, 186, 186));
        jTextField7.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jTextField7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 272, 59, 39));

        jTextField8.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jTextField8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField8.setText("3");
        jTextField8.setToolTipText("");
        jTextField8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 270, 59, 39));

        jTextField9.setBackground(new java.awt.Color(186, 186, 186));
        jTextField9.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jTextField9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 320, 59, 39));

        jTextField10.setBackground(new java.awt.Color(186, 186, 186));
        jTextField10.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jTextField10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, 59, 39));

        jTextField11.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jTextField11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField11.setText("4");
        jTextField11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextField11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField11ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 320, 59, 39));

        jTextField13.setBackground(new java.awt.Color(186, 186, 186));
        jTextField13.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jTextField13.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextField13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField13ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 370, 59, 39));

        jTextField14.setBackground(new java.awt.Color(186, 186, 186));
        jTextField14.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jTextField14.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextField14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField14ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField14, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 368, 59, 39));

        jTextField15.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jTextField15.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField15.setText("2");
        jTextField15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextField15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField15ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField15, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 368, 59, 39));

        jTextField16.setBackground(new java.awt.Color(186, 186, 186));
        jTextField16.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jTextField16.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextField16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField16ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField16, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 368, 59, 39));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sudoku/ezgif.com-gif-maker__7_-removebg-preview-removebg-preview.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 400, -1));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("New Game");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, -1, 40));

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Rules");
        jButton3.setMaximumSize(new java.awt.Dimension(109, 29));
        jButton3.setMinimumSize(new java.awt.Dimension(109, 29));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 440, 110, 40));

        jTextField12.setBackground(new java.awt.Color(186, 186, 186));
        jTextField12.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jTextField12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextField12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField12ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 320, 59, 39));

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Exit");
        jButton4.setMaximumSize(new java.awt.Dimension(109, 29));
        jButton4.setMinimumSize(new java.awt.Dimension(109, 29));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 440, 110, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sudoku/photo-1607513746994-51f730a44832.jpg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 490));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(192, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 493, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   
    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        
        String value1;
        value1=jTextField1.getText();
        int num;
        num=Integer.parseInt(value1);
        if(num>0 && num<5){
        if(value1.equals(jTextField3.getText())){
            jTextField1.setBackground(Color.red);
            jTextField1.setText(value1);
        }
        else if(value1.equals(jTextField5.getText())){
            jTextField1.setBackground(Color.red);
            jTextField1.setText(value1);
        }
        else if(value1.equals(jTextField6.getText())){
            jTextField1.setBackground(Color.red);
            jTextField1.setText(value1);
        }
        else if(value1.equals(jTextField2.getText())){
            jTextField1.setBackground(Color.red);
            jTextField1.setText(value1);
        }
        else if(value1.equals(jTextField9.getText())){
            jTextField1.setBackground(Color.red);
            jTextField1.setText(value1);
        }
        else if(value1.equals(jTextField16.getText())){
            jTextField1.setBackground(Color.red);
            jTextField1.setText(value1);
        }
        else if(value1.equals(jTextField4.getText())){
            jTextField1.setBackground(Color.red);
            jTextField1.setText(value1);
        }
        
        else{
        jTextField1.setBackground(Color.white);
        jTextField1.setText(value1);
    }
        }
        else{
            JOptionPane.showMessageDialog(null, "Please Enter Number between 1 and 4");
        }
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
          String value1;
        value1=jTextField2.getText();
        int num;
        num=Integer.parseInt(value1);
        if(num>0 && num<5){
        if(value1.equals(jTextField1.getText())){
            jTextField2.setBackground(Color.red);
            jTextField2.setText(value1);
        }
        else if(value1.equals(jTextField4.getText())){
            jTextField2.setBackground(Color.red);
            jTextField2.setText(value1);
        }
        else if(value1.equals(jTextField3.getText())){
            jTextField2.setBackground(Color.red);
            jTextField2.setText(value1);
        }
        else if(value1.equals(jTextField10.getText())){
            jTextField2.setBackground(Color.red);
            jTextField2.setText(value1);
        }
        else if(value1.equals(jTextField15.getText())){
            jTextField2.setBackground(Color.red);
            jTextField2.setText(value1);
        }
        else if(value1.equals(jTextField5.getText())){
            jTextField2.setBackground(Color.red);
            jTextField2.setText(value1);
        }
        else if(value1.equals(jTextField6.getText())){
            jTextField1.setBackground(Color.red);
            jTextField1.setText(value1);
        }
        
        else{
        jTextField2.setBackground(Color.white);
        jTextField2.setText(value1);
    }
        }
        else{
            JOptionPane.showMessageDialog(null, "Please Enter Number between 1 and 4");
        }
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
  String value1;
        value1=jTextField4.getText();
        int num;
        num=Integer.parseInt(value1);
        if(num>0 && num<5){
        if(value1.equals(jTextField1.getText())){
            jTextField4.setBackground(Color.red);
            jTextField4.setText(value1);
        }
        else if(value1.equals(jTextField2.getText())){
            jTextField4.setBackground(Color.red);
            jTextField4.setText(value1);
        }
        else if(value1.equals(jTextField7.getText())){
            jTextField4.setBackground(Color.red);
            jTextField4.setText(value1);
        }
        else if(value1.equals(jTextField11.getText())){
            jTextField4.setBackground(Color.red);
            jTextField4.setText(value1);
        }
        else if(value1.equals(jTextField14.getText())){
            jTextField4.setBackground(Color.red);
            jTextField4.setText(value1);
        }
        else if(value1.equals(jTextField8.getText())){
            jTextField4.setBackground(Color.red);
            jTextField4.setText(value1);
        }
        else if(value1.equals(jTextField3.getText())){
            jTextField4.setBackground(Color.red);
            jTextField4.setText(value1);
        }
        else{
        jTextField4.setBackground(Color.white);
        jTextField4.setText(value1);
    }        
        }
        else{
            JOptionPane.showMessageDialog(null, "Please Enter Number between 1 and 4");
        }
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        jTextField3.setText("4");
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        jTextField8.setText("3");
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField11ActionPerformed
       jTextField11.setText("4");
    }//GEN-LAST:event_jTextField11ActionPerformed

    private void jTextField15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField15ActionPerformed
        jTextField2.setText("2");
    }//GEN-LAST:event_jTextField15ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        jTextField5.setText("1");
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        String value1;
        value1=jTextField6.getText();
        int num;
        num=Integer.parseInt(value1);
        if(num>0 && num<5){
        if(value1.equals(jTextField1.getText())){
            jTextField6.setBackground(Color.red);
            jTextField6.setText(value1);
        }
        else if(value1.equals(jTextField5.getText())){
            jTextField6.setBackground(Color.red);
            jTextField6.setText(value1);
        }
        else if(value1.equals(jTextField7.getText())){
            jTextField6.setBackground(Color.red);
            jTextField6.setText(value1);
        }
        else if(value1.equals(jTextField10.getText())){
            jTextField6.setBackground(Color.red);
            jTextField6.setText(value1);
        }
        else if(value1.equals(jTextField15.getText())){
            jTextField6.setBackground(Color.red);
            jTextField6.setText(value1);
        }
        else if(value1.equals(jTextField8.getText())){
            jTextField6.setBackground(Color.red);
            jTextField6.setText(value1);
        }
        else if(value1.equals(jTextField2.getText())){
            jTextField6.setBackground(Color.red);
            jTextField6.setText(value1);
        }
        else{
        jTextField6.setBackground(Color.white);
        jTextField6.setText(value1);
    }        
        }
        else{
            JOptionPane.showMessageDialog(null, "Please Enter Number between 1 and 4");
        }
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        String value1;
        value1=jTextField7.getText();
        int num;
        num=Integer.parseInt(value1);
        if(num>0 && num<5){
        if(value1.equals(jTextField4.getText())){
            jTextField7.setBackground(Color.red);
            jTextField7.setText(value1);
        }
        else if(value1.equals(jTextField5.getText())){
            jTextField7.setBackground(Color.red);
            jTextField7.setText(value1);
        }
        else if(value1.equals(jTextField3.getText())){
            jTextField7.setBackground(Color.red);
            jTextField7.setText(value1);
        }
        else if(value1.equals(jTextField11.getText())){
            jTextField7.setBackground(Color.red);
            jTextField7.setText(value1);
        }
        else if(value1.equals(jTextField14.getText())){
            jTextField7.setBackground(Color.red);
            jTextField7.setText(value1);
        }
        else if(value1.equals(jTextField8.getText())){
            jTextField7.setBackground(Color.red);
            jTextField7.setText(value1);
        }
        else if(value1.equals(jTextField6.getText())){
            jTextField7.setBackground(Color.red);
            jTextField7.setText(value1);
        }
        else{
        jTextField7.setBackground(Color.white);
        jTextField7.setText(value1);
    }  
        }
        else{
            JOptionPane.showMessageDialog(null, "Please Enter Number between 1 and 4");
        }
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        String value1;
        value1=jTextField9.getText();
        int num;
        num=Integer.parseInt(value1);
        if(num>0 && num<5){
        if(value1.equals(jTextField1.getText())){
            jTextField9.setBackground(Color.red);
            jTextField9.setText(value1);
        }
        else if(value1.equals(jTextField5.getText())){
            jTextField9.setBackground(Color.red);
            jTextField9.setText(value1);
        }
        else if(value1.equals(jTextField16.getText())){
            jTextField9.setBackground(Color.red);
            jTextField9.setText(value1);
        }
        else if(value1.equals(jTextField11.getText())){
            jTextField9.setBackground(Color.red);
            jTextField9.setText(value1);
        }
        else if(value1.equals(jTextField10.getText())){
            jTextField9.setBackground(Color.red);
            jTextField9.setText(value1);
        }
        else if(value1.equals(jTextField12.getText())){
            jTextField9.setBackground(Color.red);
            jTextField9.setText(value1);
        }
        else if(value1.equals(jTextField15.getText())){
            jTextField9.setBackground(Color.red);
            jTextField9.setText(value1);
        }
        else{
        jTextField9.setBackground(Color.white);
        jTextField9.setText(value1);
    }  
        }
        else{
            JOptionPane.showMessageDialog(null, "Please Enter Number between 1 and 4");
        }
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed
        String value1;
        value1=jTextField10.getText();
        int num;
        num=Integer.parseInt(value1);
        if(num>0 && num<5){
        if(value1.equals(jTextField2.getText())){
            jTextField10.setBackground(Color.red);
            jTextField10.setText(value1);
        }
        else if(value1.equals(jTextField6.getText())){
            jTextField10.setBackground(Color.red);
            jTextField10.setText(value1);
        }
        else if(value1.equals(jTextField15.getText())){
            jTextField10.setBackground(Color.red);
            jTextField10.setText(value1);
        }
        else if(value1.equals(jTextField11.getText())){
            jTextField10.setBackground(Color.red);
            jTextField10.setText(value1);
        }
        else if(value1.equals(jTextField9.getText())){
            jTextField10.setBackground(Color.red);
            jTextField10.setText(value1);
        }
        else if(value1.equals(jTextField12.getText())){
            jTextField10.setBackground(Color.red);
            jTextField10.setText(value1);
        }
        else if(value1.equals(jTextField16.getText())){
            jTextField10.setBackground(Color.red);
            jTextField10.setText(value1);
        }
        else{
        jTextField10.setBackground(Color.white);
        jTextField10.setText(value1);
    }  
        }
        else{
            JOptionPane.showMessageDialog(null, "Please Enter Number between 1 and 4");
        }
    }//GEN-LAST:event_jTextField10ActionPerformed

    private void jTextField16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField16ActionPerformed
        String value1;
        value1=jTextField16.getText();
        int num;
        num=Integer.parseInt(value1);
        if(num>0 && num<5){
        if(value1.equals(jTextField1.getText())){
            jTextField16.setBackground(Color.red);
            jTextField16.setText(value1);
        }
        else if(value1.equals(jTextField5.getText())){
            jTextField16.setBackground(Color.red);
            jTextField16.setText(value1);
        }
        else if(value1.equals(jTextField9.getText())){
            jTextField16.setBackground(Color.red);
            jTextField16.setText(value1);
        }
        else if(value1.equals(jTextField15.getText())){
            jTextField16.setBackground(Color.red);
            jTextField16.setText(value1);
        }
        else if(value1.equals(jTextField14.getText())){
            jTextField16.setBackground(Color.red);
            jTextField16.setText(value1);
        }
        else if(value1.equals(jTextField13.getText())){
            jTextField16.setBackground(Color.red);
            jTextField16.setText(value1);
        }
        else if(value1.equals(jTextField10.getText())){
            jTextField16.setBackground(Color.red);
            jTextField16.setText(value1);
        }
        else{
        jTextField16.setBackground(Color.white);
        jTextField16.setText(value1);
    }
        }
        else{
            JOptionPane.showMessageDialog(null, "Please Enter Number between 1 and 4");
        }
    }//GEN-LAST:event_jTextField16ActionPerformed

    private void jTextField14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField14ActionPerformed
        String value1;
        value1=jTextField14.getText();
        int num;
        num=Integer.parseInt(value1);
        if(num>0 && num<5){
        if(value1.equals(jTextField4.getText())){
            jTextField14.setBackground(Color.red);
            jTextField14.setText(value1);
        }
        else if(value1.equals(jTextField7.getText())){
            jTextField14.setBackground(Color.red);
            jTextField14.setText(value1);
        }
        else if(value1.equals(jTextField11.getText())){
            jTextField14.setBackground(Color.red);
            jTextField14.setText(value1);
        }
        else if(value1.equals(jTextField16.getText())){
            jTextField14.setBackground(Color.red);
            jTextField14.setText(value1);
        }
        else if(value1.equals(jTextField15.getText())){
            jTextField14.setBackground(Color.red);
            jTextField14.setText(value1);
        }
        else if(value1.equals(jTextField13.getText())){
            jTextField14.setBackground(Color.red);
            jTextField14.setText(value1);
        }
        else if(value1.equals(jTextField12.getText())){
            jTextField14.setBackground(Color.red);
            jTextField14.setText(value1);
        }
        else{
        jTextField14.setBackground(Color.white);
        jTextField14.setText(value1);
    }
        }
        else{
            JOptionPane.showMessageDialog(null, "Please Enter Number between 1 and 4");
        }
    }//GEN-LAST:event_jTextField14ActionPerformed

    private void jTextField13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField13ActionPerformed
        String value1;
        value1=jTextField13.getText();
        int num;
        num=Integer.parseInt(value1);
        if(num>0 && num<5){
        if(value1.equals(jTextField3.getText())){
            jTextField13.setBackground(Color.red);
            jTextField13.setText(value1);
        }
        else if(value1.equals(jTextField8.getText())){
            jTextField13.setBackground(Color.red);
            jTextField13.setText(value1);
        }
        else if(value1.equals(jTextField12.getText())){
            jTextField13.setBackground(Color.red);
            jTextField13.setText(value1);
        }
        else if(value1.equals(jTextField16.getText())){
            jTextField13.setBackground(Color.red);
            jTextField13.setText(value1);
        }
        else if(value1.equals(jTextField15.getText())){
            jTextField13.setBackground(Color.red);
            jTextField13.setText(value1);
        }
        else if(value1.equals(jTextField14.getText())){
            jTextField13.setBackground(Color.red);
            jTextField13.setText(value1);
        }
        else if(value1.equals(jTextField11.getText())){
            jTextField13.setBackground(Color.red);
            jTextField13.setText(value1);
        }
        else{
        jTextField13.setBackground(Color.white);
        jTextField13.setText(value1);
    }
        }
        else{
            JOptionPane.showMessageDialog(null, "Please Enter Number between 1 and 4");
        }
    }//GEN-LAST:event_jTextField13ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        jTextField1.setText("");
        jTextField1.setBackground(Color.lightGray);
        jTextField2.setText("");
        jTextField2.setBackground(Color.lightGray);
        jTextField4.setText("");
        jTextField4.setBackground(Color.lightGray);
        jTextField6.setText("");
        jTextField6.setBackground(Color.lightGray);
        jTextField7.setText("");
        jTextField7.setBackground(Color.lightGray);
        jTextField9.setText("");
        jTextField9.setBackground(Color.lightGray);
        jTextField10.setText("");
        jTextField10.setBackground(Color.lightGray);
        jTextField12.setText("");
        jTextField12.setBackground(Color.lightGray);
        jTextField16.setText("");
        jTextField16.setBackground(Color.lightGray);
        jTextField14.setText("");
        jTextField14.setBackground(Color.lightGray);
        jTextField13.setText("");
        jTextField13.setBackground(Color.lightGray);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        rules r = new rules();
        r.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField12ActionPerformed
        String value1;
        value1=jTextField12.getText();
        int num;
        num=Integer.parseInt(value1);
        if(num>0 && num<5){
        if(value1.equals(jTextField3.getText())){
            jTextField12.setBackground(Color.red);
            jTextField12.setText(value1);
        }
        else if(value1.equals(jTextField8.getText())){
            jTextField12.setBackground(Color.red);
            jTextField12.setText(value1);
        }
        else if(value1.equals(jTextField13.getText())){
            jTextField12.setBackground(Color.red);
            jTextField12.setText(value1);
        }
        else if(value1.equals(jTextField11.getText())){
            jTextField12.setBackground(Color.red);
            jTextField12.setText(value1);
        }
        else if(value1.equals(jTextField9.getText())){
            jTextField12.setBackground(Color.red);
            jTextField12.setText(value1);
        }
        else if(value1.equals(jTextField10.getText())){
            jTextField12.setBackground(Color.red);
            jTextField12.setText(value1);
        }
        else if(value1.equals(jTextField14.getText())){
            jTextField12.setBackground(Color.red);
            jTextField12.setText(value1);
        }
        else{
        jTextField12.setBackground(Color.white);
        jTextField12.setText(value1);
    }
            
        }
        else{
            JOptionPane.showMessageDialog(null, "Please Enter Number between 1 and 4");
        }
    }//GEN-LAST:event_jTextField12ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton4ActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
